force-app/main/default/objects/Storage_Unit__c/Storage_Unit__c.object-meta.xml
<CustomObject>
    <label>Storage Unit</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Storage Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Storage Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Storage_Unit__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <type>TextArea</type>
</CustomField>

rentaspace/main/default/objects/Storage_Unit__c/fields/Storage_Account__c.field-meta.xml
<CustomField>
    <fullName>Storage_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Storage Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Storage Units</relationshipLabel>
    <relationshipName>Storage_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactsController.cls
public class ContactsController {
    @AuraEnabled
    public static List<Storage_Unit__c> get10COntacts()
    {   
        String account = '0015f00000DC0ZpAAL';
        return [SELECT NAME, Nickname__c FROM Storage_Unit__c WHERE Storage_Account__c = :account];       
    }

    @AuraEnabled
    public static List<Storage_Unit__c> get10COntacts(String account)
    {   
        //acount variable is the id, not the name
        return [SELECT NAME, Nickname__c FROM Storage_Unit__c WHERE Storage_Account__c = :account];
    }

    @AuraEnabled
    public static List<Storage_Unit__c> get11COntacts(){
        System.debug('Reached get11 in apex');
        String account = '0015f00000DC0ZpAAL';
        return [SELECT NAME, Nickname__c, CreatedById FROM Storage_Unit__c WHERE Storage_Account__c = :account];     
    }
}