force-app/main/default/objects/Storage_Unit__c/Storage_Unit__c.object-meta.xml
<CustomObject>
    <label>Storage Unit</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Storage Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Storage Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

rentaspace/main/default/objects/Storage_Unit__c/fields/Storage_Account__c.field-meta.xml
<CustomField>
    <fullName>Storage_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Storage Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Storage Units</relationshipLabel>
    <relationshipName>Storage_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testStorage.cls
@isTest
public class testStorage {
    @isTest static void testStorageController(){
        //tests the response class for the apex trigger associated with it. 
        System.debug(getStorageUnitDataController.getStorageUnits());
    }
    @isTest static void testContactsController(){
        //test base method
        System.debug(ContactsController.get10COntacts());
        //test overloaded version that takes account name
        System.debug(ContactsController.get10COntacts('Dickenson plc'));
        //tests the secondary method 
        System.debug(ContactsController.get11COntacts());
    }
     @isTest static void testTriggersBlank(){
        Storage_Unit__c storage = new Storage_Unit__c();
        insert storage;
        update storage;
        delete storage;
    }
     @isTest static void testTriggersFull(){
        Storage_Unit__c storage = new Storage_Unit__c();
        storage.Storage_Account__c = '0015f00000DC0ZpAAL';
        insert storage;
        storage.Storage_Account__c = '0015f00000DC0ZpAAL';
        update storage;
         
    }
}