rentaspace/main/default/objects/Storage_Location__c/Storage_Location__c.object-meta.xml
<CustomObject>
    <label>Storage Location</label>
    <nameField>
        <label>Storage Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Storage Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Storage_Unit__c/Storage_Unit__c.object-meta.xml
<CustomObject>
    <label>Storage Unit</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Storage Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Storage Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Storage_Unit__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <description>Length of the Storage Unit.</description>
    <label>Length</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

rentaspace/main/default/objects/Storage_Unit__c/fields/Storage_Account__c.field-meta.xml
<CustomField>
    <fullName>Storage_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Storage Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Storage Units</relationshipLabel>
    <relationshipName>Storage_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

rentaspace/main/default/objects/Storage_Unit__c/fields/Storage_Location__c.field-meta.xml
<CustomField>
    <fullName>Storage_Location__c</fullName>
    <label>Storage Location</label>
    <referenceTo>Storage_Location__c</referenceTo>
    <relationshipLabel>Storage Units</relationshipLabel>
    <relationshipName>Storage_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Storage_Unit__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <description>Width of the Storage Unit.</description>
    <label>Width</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

rentaspace/main/default/classes/testStorageUnitTrigger.cls
@isTest public class testStorageUnitTrigger {
    @isTest static void testTrigger(){
        Test.startTest();
		Storage_Unit__c storage = new Storage_Unit__c();
        storage.Storage_Account__c = '0015f00000DC0ZpAAL';
        storage.Storage_Location__c = 'a015f00000Ej3TAAAZ';
        storage.Width__c = 5;
        storage.Length__c = 5;
        
        insert storage;
        Test.stopTest();
    }
}